version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alifandika_app
    ports:
      - "8000:80"  
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: pgsql
      DB_DATABASE: alifandika
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - pgsql

  pgsql:
    image: postgres:15
    container_name: alifandika_pgsql
    restart: always
    environment:
      POSTGRES_DB: alifandika
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
